# Generated by Django 5.2.5 on 2025-09-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_logo', models.ImageField(upload_to='logo/')),
                ('welcome_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SliderBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
